INSERT INTO customer (id, name, email, address) VALUES
(1, 'Mariazinha', 'mariazinha@email.com', '799 DuBuque Meadow'),
(2, 'Ciclano', 'ciclano@email.com','843 Rogahn Port'),
(3, 'Joãozinho', 'joaozinho@email.com','852 Crist Crossing'),
(4, 'Snagmotur', 'Snagmotur@email.com','2700 Hayes Canyon'),
(5, 'Saupi', 'Saupi@email.com','75957 Hammes Club'),
(6, 'Hud', 'Hud@email.com','08821 Clementine Causeway'),
(7, 'Guarul', 'Guarul@email.com','162O Kon Causeway'),
(8, 'Weikeogu', 'Weikeogu@email.com','385 Heidenreich Lake'),
(9, 'Duerkairic', 'Duerkairic@email.com','624 Runte Locks'),
(10, 'Shakndar', 'Shakndar@email.com','081 Terrence Walk'),
(11, 'Locerou', 'Locerou@email.com','9341 Greenfelder Corners'),
(12, 'Branihub', 'Branihub@email.com','67839 Borer Mill'),
(13, 'Adanbiron', 'Adanbiron@email.com','584 Monahan Turnpike'),
(14, 'Kurzgakh', 'Kurzgakh@email.com',''),
(15, 'Uldodir', 'Uldodir@email.com','1911 Dibbert Walks'),
(16, 'Linzaho', 'Linzaho@email.com','089 Sabina Fall'),
(17, 'Voikorre', 'Voikorre@email.com','2064 Mayer Row'),
(18, 'Caxapen', 'Caxapen@email.com','4075 Zoe River'),
(19, 'Nuol', 'Nuol@email.com','58363 Laverne Spring'),
(20, 'Linuil', 'Linuil@email.com','55847 Margaret Fords'),
(21, 'Rearandir', 'Rearandir@email.com','8180 Smith Track'),
(22, 'Kopu', 'Kopu@email.com','84449 Jakubowski Lakes'),
(23, 'Cudaidu', 'Cudaidu@email.com','5651 Kenna Ridge'),
(24, 'Batauru', 'Batauru@email.com','053 Lorenza Estates'),
(25, 'Aranor', 'Aranor@email.com','22825 Kessler Run'),
(26, 'Wiaba', 'Wiaba@email.com','977 Wuckert Highway'),
(27, 'Usisr', 'Usisr@email.com','589 Hickle Expressway'),
(28, 'Atuog', 'Atuog@email.com','81827 Schoen Square'),
(29, 'Miude', 'Miude@email.com','99236 Jerde Freeway'),
(30, 'Ires', 'Ires@email.com','55336 Bayer Mills');
